### ISSUE TITLE
Error messages not appearing

### ISSUE THREAD

**Issue by jaypanares** [fabienb4/meteor-autoform-semantic-ui#13]
Hi, the validation messages don't seem to be appearing on my quickform:

`{{> quickForm schema="Schema" id="inputForm" template="semanticUI"}}`

The inputs turn red and are working fine when validation fails, but I don't see the messages that are supposed to appear when validation fails.  I'm using the semantic:ui (the LESS version) if that makes a difference.  Thanks!

**Comment by fabienb4** [comment]
Semantic-ui does not provide per field error message by default. See semantic-ui [docs](http://semantic-ui.com/collections/form.html).

You can either display messages on your own, or use the [custom option](https://github.com/fabienb4/meteor-autoform-semantic-ui#show-errors-in-label) to display them in the label.

Otherwise, the messages are actually outputted to HTML, but semantic-ui isn't displaying them, you should be able to customize the `.field > .error.message` CSS class, to specify how to display them.
