### ISSUE TITLE
Hardcoded label "Clear" in select input 

### ISSUE THREAD

**Issue by kifirkin** [fabienb4/meteor-autoform-semantic-ui#15]
Hi, can be label for clear button passed as arguments or removed?

**Comment by fabienb4** [comment]
For an optional field, without the clear button the user has no way to reset the select. I can make it so that you can change the label but I think "Clear" is pretty... clear.

For a required field, the clear button should not appear.

Maybe there is a special case I'm not seeing, if so please expand your thoughts on the matter.

**Comment by kifirkin** [comment]
Oh I see, I mean that it cannot be translated into different language or similar issues.
Maybe just place only eraser icon?

**Comment by fabienb4** [comment]
Oh OK, that might be good yeah. Let me see what I can do.

**Comment by kifirkin** [comment]
Thanks a lot! :+1:
