### ISSUE TITLE
cannot pass object to custom form attribute in quickform

### ISSUE THREAD

**Issue by akshaykmr** [fabienb4/meteor-autoform-semantic-ui#23]
take this quickform for example

``` html
{{> quickForm 
            schema=addressSchema
            id="addressForm"
            type="method"
            meteormethod="addAddress"
            myCustomAttribute=getAttr
}}
```

helper

``` javascript
Template.addressForm.helpers({
    'getAttr': function(){
        return {some: 'data'};
    }
});
```

I usually add a custom attribute for help in the form hooks. It works fine when using only the autoform package but when using the this package I'm not able to pass object. returning a string works but upon returning object I get the following error in console and the form doesn't load at all.

```
Uncaught Error: Unexpected object in htmljs in toText: [object Object]

```

**Comment by abernix** [comment]
The error is caused because of differences in the `autoFormTplAtts` method in meteor-autoform-semantic-ui.  The newer version does additional checking to prevent this error from happening.

While it doesn't cause an error in the regular autoform (and this version should be patched), my tests don't show your code _actually_ causing any changes to the outputted HTML.  Are you sure that something on the `form` tag is changing when you add `myCustomAttribute=getAttr`?

Basically, I don't quite understand what your intended result of this code is.  How are you going to store a JSON object in an HTML element?

If you're trying to have dynamic attributes for the `<form>` element, you could just create a general helper that returned everything the form needed:

``` javascript
Template.addressForm.helpers({
  autoFormAttributes: function () {
    return {
      schema: addressSchema,
      id: "addressForm",
      type: "method",
      meteormethod: "addAddress",
      some: "data",
      otherCustom: "attributes"
    };
  }
});
```

and then in your HTML:

```
{{#autoForm autoFormAttributes}}
```

**Comment by akshaykmr** [comment]
https://github.com/aldeed/meteor-autoform/issues/907
see afriC84 comment. That is what I'm trying to do

**Comment by abernix** [comment]
Got it.  That makes sense then.

Just submitted patch #24 which will fix it for you if you want to give it a shot.

**Comment by akshaykmr** [comment]
will check it out later today. thanks :)

**Comment by fabienb4** [comment]
Merged the commit. Tell me if you still have issues.

Thanks @abernix.
